yarnPath: .yarn/releases/yarn-3.6.0.cjs
nodeLinker: node-modules

logFilters:
  - level: discard
    pattern: "doesn't satisfy what @docusaurus/"
  - level: discard
    pattern: "doesn't satisfy what @mdx-js/react"
  - level: discard
    pattern: "doesn't provide @algolia/client-search"
