logFilters:
  - level: discard
    pattern: doesn't satisfy what @docusaurus/
  - level: discard
    pattern: doesn't satisfy what @mdx-js/react
  - level: discard
    pattern: doesn't provide @algolia/client-search

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
