image:
  name: ghcr.io/quantified-uncertainty/metaforecast
  tag: latest # in production for QURI, we use argocd-image-updater to update the tag

# Secret; you should create this in your k8s cluster.
envSecret: metaforecast-env

jobs:
  scheduler:
    command:
      [
        "tsx",
        "src/backend/flow/doEverythingForScheduler.ts",
      ]
    schedule: "0 3 * * *" # every day at 3am
  frontpage:
    command:
      ["tsx", "src/backend/index.ts", "frontpage"]
    schedule: "0 6 * * *" # every day at 6am
