name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: quantified-uncertainty
  # used by turbo cache hashes, see turbo.json
  PLATFORM: github

jobs:
  build-test-lint:
    name: Build, test, lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Turbo run
        run: npx turbo run build test lint bundle

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Coverage
        run: npx turbo run coverage

  # TODO - prisma migrate

  deploy:
    # Based on https://vercel.com/guides/how-can-i-use-github-actions-with-vercel
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: build-test-lint
    environment:
      name: Preview – squiggle-components
      url: https://squiggle-components-pr-${{ github.event.pull_request.number }}-quantified-uncertainty.vercel.app
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_COMPONENTS_PROJECT_ID }} # TODO - make reusable
      env: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
      dir: packages/components
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Pull Vercel Environment Information
        working-directory: ${{ env.dir }}
        run: npx vercel pull --yes --environment=${{ env.env }} --token=${{ secrets.VERCEL_API_TOKEN }}

      - name: Build Project Artifacts
        working-directory: ${{ env.dir }}
        run: npx vercel build --token=${{ secrets.VERCEL_API_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: ${{ env.dir }}
        run: |
          npx vercel deploy --prebuilt ${{ env.env == 'production' && '--prod' || '' }} --token=${{ secrets.VERCEL_API_TOKEN }} >vercel-deploy-url.txt
          vercel alias set $(cat ./vercel-deploy-url.txt) squiggle-components-pr-${{ github.event.pull_request.number }}-quantified-uncertainty.vercel.app --token=${{ secrets.VERCEL_API_TOKEN }}
