name: Prisma Migrate Preview DB

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            prisma:
              - 'packages/hub/prisma/migrations/**'

  migrate:
    needs: needs-migrate
    if: needs.needs-migrate.outputs.prisma == 'true'
    runs-on: ubuntu-latest
    environment: Preview
    steps:
    
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Migrate
        working-directory: ./packages/hub
        env:
          DATABASE_URL: "${{ secrets.DATABASE_DIRECT_URL }}"
        run: npx prisma migrate deploy
