name: Release

on: workflow_dispatch

# not needed while we don't run this workflow automatically
# concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build changelog script
        working-directory: packages/ops
        run: pnpm turbo build

      # important so that we could bump System.version
      - name: Build squiggle-lang
        working-directory: packages/squiggle-lang
        run: pnpm turbo build

      # if there are existing changesets, PR will be created.
      # Otherwise, `publish` command will be invoked.
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          title: New release
          version: pnpm run changeset-version
          publish: turbo lint build && changeset publish && cd packages/vscode-ext && pnpm run package && npx vsce publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
